name: Django CI

on:
  push:
    branches: [ "main", "pipline_testing" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # allows manual triggering


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Python 3.10.12
      run: |
        sudo apt update
        sudo apt install -y python3.10 python3.10-venv python3.10-dev
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
        python3 --version

    - name: Upgrade pip
      run: python3 -m pip install --upgrade pip

    - name: Install Dependencies
      run: |
        if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi

    - name: Run Django Tests
      run: |
        cd Quizzical || exit 1
        python3 manage.py test

