name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # allows manual triggering


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Python 3.10.12
      run: |
        sudo apt update
        sudo apt-get install python3.10

    - name: Upgrade pip
      run: python3 -m pip install --upgrade pip

    - name: Install Dependencies
      run: |
        if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi

    - name: Run Django Tests
      run: |
        cd Quizzical || exit 1
        python3 manage.py test

